version: '3.9'
services:
  postgres:
    image: postgres:14
    container_name: chocochoco-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chocochoco_indexer
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  indexer:
    build:
      context: ..
      dockerfile: indexer/Dockerfile
    container_name: chocochoco-indexer
    env_file:
      - .env.production
    ports:
      - "3001:3001"
    depends_on:
      - postgres

volumes:
  pgdata:
