[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
chocochoco_game = "J5GgxY8zobKvjJovnENncHDLWVQ2gBPH2skhTKL8JuGz"

[programs.devnet]
chocochoco_game = "J5GgxY8zobKvjJovnENncHDLWVQ2gBPH2skhTKL8JuGz"

[programs.testnet]
chocochoco_game = "J5GgxY8zobKvjJovnENncHDLWVQ2gBPH2skhTKL8JuGz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

[[test.validator.clone]]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
